from twitchAPI.type import AuthScope,ChatEvent

CLIENT_ID = "YOUR CLIENT ID"
CLIENT_SECRET = "YOUR CLIENT SECRET"
USER_SCOPE = [AuthScope.CHAT_READ,AuthScope.CHAT_EDIT,AuthScope.CHANNEL_MANAGE_BROADCAST]
TARGET_CHANNEL = "YOUR CHANNEL NAME"
